# Generated by Django 2.0.5 on 2020-01-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='encode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
