# Generated by Django 2.0.5 on 2020-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20200114_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
