# Generated by Django 2.0.5 on 2020-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20200114_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='encode',
        ),
    ]
