# Generated by Django 2.0.5 on 2020-01-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20200115_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='ward',
            field=models.CharField(blank=True, choices=[('0', 'All Ward'), ('lmc2', 'LMC 2'), ('lmc9', 'LMC 9'), ('lmc11', 'LMC 11'), ('kmc10', 'KMC 10'), ('kmc12', 'KMC 12'), ('kmc31', 'KMC 31')], max_length=15, null=True),
        ),
    ]
